# Generated by Django 5.2.7 on 2026-03-18 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text="User's message/query")),
                ('response', models.TextField(blank=True, help_text="AI's response", null=True)),
                ('sql_query', models.TextField(blank=True, help_text='Generated SQL query', null=True)),
                ('query_result', models.JSONField(blank=True, help_text='Query execution result', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_ai_response', models.BooleanField(default=True, help_text='Whether this is an AI response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['-timestamp'],
            },
        ),
    ]
